### ISSUE TITLE
Receiving an exception when launching the game

### ISSUE THREAD

**Issue by ChristopherHaws** [DarkKronicle/DarkKore#2]
```
[22:12:57] [Render thread/WARN]: Couldn't convert ffffffff into a color!
java.lang.NumberFormatException: For input string: "ff"
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.8) ~[?:?]
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:668) ~[?:?]
	at java.lang.Integer.parseInt(Integer.java:786) ~[?:?]
	at io.github.darkkronicle.darkkore.colors.Colors.hexToSimple(Colors.java:159) ~[DarkKore-0.2.2-1.19.jar:?]
	at io.github.darkkronicle.darkkore.colors.Colors.load(Colors.java:59) ~[DarkKore-0.2.2-1.19.jar:?]
	at io.github.darkkronicle.darkkore.config.ConfigurationManager.load(ConfigurationManager.java:32) ~[DarkKore-0.2.2-1.19.jar:?]
	at net.minecraft.client.MinecraftClient.handler$zpn000$init(MinecraftClient:8950) ~[?:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient:670) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:205) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.prismlauncher.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:176) [NewLaunch.jar:?]
	at org.prismlauncher.impl.OneSixLauncher.launch(OneSixLauncher.java:186) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]
```

**Comment by ChristopherHaws** [comment]
Nevermind. Prism Launcher installed v0.2.2 instead of v0.3.1 because 0.3.1 doesnt target 1.19.2 on modrinth or curseforge.
