### ISSUE TITLE
1.19.4 Resource pack loading bug

### ISSUE THREAD

**Issue by itsMarkiS** [DarkKronicle/DarkKore#5]
resourcepacks resets everytime you try, no matter which resource pack it is, it will always send the default minecraft error message like "failed to load resources"
tested every single mod and darkkore mods (kronhud and betterblockoutline) are the only ones which causes this error

23:35:15.045
net.minecraft.class_310
Render thread
Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:791)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_1255.method_18859(class_1255.java:198)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:163)
	at net.minecraft.class_1255.method_5383(class_1255.java:140)
	at net.minecraft.class_310.method_1523(class_310.java:1174)
	at net.minecraft.class_310.method_1514(class_310.java:801)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "String.indexOf(int)" because "resourceName" is null
	at net.minecraft.class_2960.method_12830(class_2960.java:88)
	at net.minecraft.class_2960.<init>(class_2960.java:51)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.rewriteAsId(FabricShaderProgram.java:42)
	at net.minecraft.class_5944.modify$bef000$fabric-rendering-v1$modifyProgramId(class_5944.java:654)
	at net.minecraft.class_5944.localvar$cpe000$optifabric$modifyProgramID(class_5944.java:2134)
	at net.minecraft.class_5944.<init>(class_5944.java:114)
	at net.minecraft.class_5944.<init>(class_5944.java:108)
	at net.fabricmc.fabric.impl.client.rendering.FabricShaderProgram.<init>(FabricShaderProgram.java:28)
	at ladysnake.satin.impl.ResettableManagedCoreShader.parseShader(ResettableManagedCoreShader.java:59)
	at ladysnake.satin.impl.ResettableManagedCoreShader.parseShader(ResettableManagedCoreShader.java:37)
	at ladysnake.satin.impl.ResettableManagedShaderBase.initialize(ResettableManagedShaderBase.java:75)
	at ladysnake.satin.impl.ResettableManagedShaderBase.initializeOrLog(ResettableManagedShaderBase.java:63)
	at ladysnake.satin.impl.ReloadableShaderEffectManager.method_14491(ReloadableShaderEffectManager.java:118)
	at net.minecraft.class_4013.method_29490(class_4013.java:15)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	... 12 more

**Comment by MrKinau** [comment]
@MarkinhosMLP why did you close this issue? It seems to be still present, although I only experience this bug with Optifabric & Optifine installed.
